# Generated by Django 5.0.1 on 2024-01-22 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contributor', models.CharField(choices=[('factory', 'Factory'), ('retail_network', 'Retail Network'), ('individual_entrepreneur', 'Individual Entrepreneur')])),
                ('email', models.EmailField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('house_number', models.CharField(max_length=10)),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_company', to='company_network.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('launch_date', models.DateField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_network.contributor')),
            ],
        ),
    ]
